local_backend: true

backend:
  name: github
  repo: wencesglace/chagris
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "cats"
    label: "Chats"
    label_singular: "Chat"
    folder: "src/content/cats"
    create: true
    delete: true
    slug: "{{year}}{{month}}{{day}}-{{fields.name}}"

    fields:
      - label: "Nom"
        name: "name"
        widget: "string"

      - label: "Age"
        name: "age"
        widget: "number"
        required: false

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Statuts"
        name: "status"
        widget: "select"
        options:
          - { label: "disponible", value: "disponible" }
          - { label: "en attente", value: "en attente" }
          - { label: "réservé", value: "réservé" }
          - { label: "famille d'accueil", value: "famille d'accueil" }

      - label: "Santé"
        name: "health"
        widget: "select"
        options:
          - { label: "fiv", value: "fiv" }
          - { label: "coryza", value: "coryza" }
        required: false

      - label: "Photo"
        name: "image"
        widget: "image"
        required: false
