name: Build and Deploy

on:
  workflow_dispatch: # trigger manuel
  repository_dispatch: # trigger externe via webhook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install deps
        run: npm install
      - name: Fetch Notion Cats
        run: node scripts/fetchCatsFromNotion.ts
      - name: Build Next.js
        run: npm run build
      - name: Deploy
        run: npm run deploy # selon ton h√©bergeur
